### ISSUE TITLE
[Suggestion] Red Power-Style cables?

### ISSUE THREAD

**Issue by LordMZTE** [Commoble/morered#1] opened 2020-06-08 13:52 UTC
what do you think of the idea of adding cables like the ones from red power which can be placed on walls and insulated in all 16 colors so they don't connect? and maybe also bundled cables?

**Comment by Commoble** [comment] 2020-06-08 21:29
These are long-term goals, yes. (closing this because it's not a bug report)

**Closed by Commoble** 2020-06-08 21:29 UTC

**Comment by LordMZTE** [comment] 2020-06-08 21:37
ah ok, id suggest stating that this isnt for bugs somewhere :D
